import { defineObject, FieldType } from 'twenty-sdk/define';

export const NAME_FIELD_UNIVERSAL_IDENTIFIER =
  'bf1c5246-b098-42ed-b07b-4e6bb9e6ef35';

export default defineObject({
  universalIdentifier: '2eb4bc89-eddc-4ea5-8a3a-4fd7d547c244',
  nameSingular: 'facebookLead',
  namePlural: 'facebookLeads',
  labelSingular: 'Facebook lead',
  labelPlural: 'Facebook leads',
  icon: 'IconUsers',
  labelIdentifierFieldMetadataUniversalIdentifier: NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the lead (author/seller)',
      icon: 'IconUser',
    },
    {
      universalIdentifier: 'b756bc83-fbf7-4281-b3a1-f3d4ef59dc2f',
      type: FieldType.TEXT,
      name: 'profileUrl',
      label: 'Profile URL',
      description: 'Facebook profile URL',
      icon: 'IconLink',
    },
    {
      universalIdentifier: '75bfd7a9-fb7c-49b8-b4fa-6ea2842a5da2',
      type: FieldType.TEXT,
      name: 'phoneNumber',
      label: 'Phone Number',
      description: 'Contact phone number',
      icon: 'IconPhone',
    },
    {
      universalIdentifier: 'c85f8204-48bc-496c-962c-45df0bba3c7f',
      type: FieldType.TEXT,
      name: 'email',
      label: 'Email',
      description: 'Contact email address',
      icon: 'IconMail',
    },
    {
      universalIdentifier: '029ccb8f-ba05-4906-849a-525e64d2341c',
      type: FieldType.TEXT,
      name: 'sourceUrl',
      label: 'Source URL',
      description: 'Original post or listing URL',
      icon: 'IconExternalLink',
    },
    {
      universalIdentifier: '7fd36c1c-173f-44d2-a2b4-530a3b12063a',
      type: FieldType.TEXT,
      name: 'title',
      label: 'Title',
      description: 'Post title or listing title',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: '3e9889cb-d0d8-4ef6-bec3-5412d62662f9',
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      description: 'Post or listing description',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: 'bd669ada-7712-46c6-bf55-d4e31f4eaa59',
      type: FieldType.TEXT,
      name: 'location',
      label: 'Location',
      description: 'Location from post or listing',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: '1151bdf3-beeb-4fdd-883e-d103bb3569ae',
      type: FieldType.TEXT,
      name: 'price',
      label: 'Price',
      description: 'Price (for marketplace listings)',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: '6df33559-861c-4aa4-9c3d-30afae0116e6',
      type: FieldType.SELECT,
      name: 'source',
      label: 'Source',
      description: 'Where the lead came from',
      icon: 'IconBrandFacebook',
      options: [
        { value: 'MARKETPLACE', label: 'Marketplace', color: 'blue', position: 0 },
        { value: 'GROUP', label: 'Group', color: 'green', position: 1 },
      ],
    },
    {
      universalIdentifier: 'aa445030-c402-43b6-9185-e6a17f466257',
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Lead status',
      icon: 'IconProgress',
      options: [
        { value: 'NEW', label: 'New', color: 'gray', position: 0 },
        { value: 'CONTACTED', label: 'Contacted', color: 'yellow', position: 1 },
        { value: 'RESPONDED', label: 'Responded', color: 'blue', position: 2 },
        { value: 'CONVERTED', label: 'Converted', color: 'green', position: 3 },
        { value: 'NOT_INTERESTED', label: 'Not Interested', color: 'red', position: 4 },
      ],
      defaultValue: "'NEW'",
    },
    {
      universalIdentifier: 'c4a7500c-2496-475c-8842-851f15fb116a',
      type: FieldType.TEXT,
      name: 'postedAt',
      label: 'Posted At',
      description: 'When the original post was made',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: '219738d0-94c6-491f-b399-222040117926',
      type: FieldType.TEXT,
      name: 'postId',
      label: 'Post ID',
      description: 'Facebook post or listing ID',
      icon: 'IconId',
    },
  ],
});
